from enum import Enum

#网址功能枚举
class UrlFunction_t(Enum):
    URL_FUNC_LOLYTT_BOOT = 0
    URL_FUNC_LOLYTT_SEARCH = 1
    URL_FUNC_BUBULAI_BOOT = 2
    URL_FUNC_SOBT_BOOT = 3
    URL_FUNC_PANSOU_BOOT = 4
    URL_FUNC_993DY_SERACH = 5
    URL_FUNC_PANSOSO_SEARCH = 6
    URL_FUNC_Y80S_SERACH = 7
    URL_FUNC_Y80S_BOOT = 8
    URL_FUNC_415_BOOT = 9
    URL_FUNC_22TU_SERACH = 10
    URL_FUNC_GAOQING_SEARCH = 11
    URL_FUNC_66TV_SEARCH = 12
    URL_FUNC_66TV_BOOT = 13
    URL_FUNC_LESTV_SEARCH = 14
    URL_FUNC_LESTV_BOOT = 15
    URL_FUNC_MUKGU_BOOT = 16
    URL_FUNC_ZHONGZI8_BOOT = 17
    URL_FUNC_618G_BOOT = 18
    URL_FUNC_IVI_BOOT = 19
    URL_FUNC_55HK_BOOT = 20
    URL_FUNC_GDTV_WL_BOOT = 21
    URL_FUNC_OWTOP_BOOT = 22
    URL_FUNC_DSZBDQ_BOOT = 23
    URL_FUNC_YUNSOSO_BOOT = 24
    URL_FUNC_IQIYI_BOOT = 25
    URL_FUNC_IQIYI_SEARCH = 26
    URL_FUNC_LTOSS_BOOT = 27
    URL_FUNC_8090G_BOOT = 28
    URL_FUNC_8090API_BOOT = 29
    URL_FUNC_8090JX_BOOT = 30
    URL_FUNC_VQQ_BOOT = 31
    URL_FUNC_BTMOVI_SEARCH = 32
    URL_FUNC_BTMOVI_BOOT = 33
    URL_FUNC_GDTV_QS_BOOT = 34
    URL_FUNC_NFMOVIE_BOOT = 35
    URL_FUNC_PIAOHUA_BOOT = 36
    URL_FUNC_1717_BOOT = 37
    URL_FUNC_GANGJU_SEARCH = 38
    URL_FUNC_GANGJU_BOOT = 39
    URL_FUNC_YOUKU_BOOT = 40
    URL_FUNC_YOUKU_SEARCH = 41