# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BatchDownUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatDownWindow(object):
    def setupUi(self, BatDownWindow):
        BatDownWindow.setObjectName("BatDownWindow")
        BatDownWindow.resize(678, 557)
        self.centralwidget = QtWidgets.QWidget(BatDownWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(5, 30, 231, 471))
        self.listView.setObjectName("listView")
        self.txtSavePath = QtWidgets.QTextEdit(self.centralwidget)
        self.txtSavePath.setGeometry(QtCore.QRect(5, 3, 561, 21))
        self.txtSavePath.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSavePath.setObjectName("txtSavePath")
        self.btnSelectPath = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectPath.setGeometry(QtCore.QRect(580, 2, 91, 23))
        self.btnSelectPath.setObjectName("btnSelectPath")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(240, 30, 431, 471))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 54, 21))
        self.label.setObjectName("label")
        self.txtFileName = QtWidgets.QTextEdit(self.groupBox)
        self.txtFileName.setGeometry(QtCore.QRect(70, 20, 351, 21))
        self.txtFileName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtFileName.setObjectName("txtFileName")
        self.txtLink = QtWidgets.QTextEdit(self.groupBox)
        self.txtLink.setGeometry(QtCore.QRect(70, 50, 351, 151))
        self.txtLink.setObjectName("txtLink")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 210, 54, 12))
        self.label_3.setObjectName("label_3")
        self.txtBaseLink = QtWidgets.QTextEdit(self.groupBox)
        self.txtBaseLink.setGeometry(QtCore.QRect(70, 210, 351, 131))
        self.txtBaseLink.setObjectName("txtBaseLink")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 350, 171, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.rb1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb1.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.rb1.setObjectName("rb1")
        self.rb2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb2.setGeometry(QtCore.QRect(10, 40, 141, 16))
        self.rb2.setObjectName("rb2")
        self.rb3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb3.setGeometry(QtCore.QRect(10, 60, 141, 16))
        self.rb3.setObjectName("rb3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(170, 350, 140, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 50, 89, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.btnDownList = QtWidgets.QPushButton(self.groupBox)
        self.btnDownList.setGeometry(QtCore.QRect(280, 440, 145, 23))
        self.btnDownList.setObjectName("btnDownList")
        self.btnAddLink = QtWidgets.QPushButton(self.groupBox)
        self.btnAddLink.setGeometry(QtCore.QRect(110, 440, 145, 23))
        self.btnAddLink.setObjectName("btnAddLink")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(309, 350, 122, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.cbSwTask = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbSwTask.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.cbSwTask.setObjectName("cbSwTask")
        self.cboTaskCount = QtWidgets.QComboBox(self.groupBox_4)
        self.cboTaskCount.setGeometry(QtCore.QRect(10, 50, 101, 22))
        self.cboTaskCount.setObjectName("cboTaskCount")
        BatDownWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BatDownWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 23))
        self.menubar.setObjectName("menubar")
        self.menuOperation = QtWidgets.QMenu(self.menubar)
        self.menuOperation.setObjectName("menuOperation")
        BatDownWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BatDownWindow)
        self.statusbar.setObjectName("statusbar")
        BatDownWindow.setStatusBar(self.statusbar)
        self.actionList_Save_As = QtWidgets.QAction(BatDownWindow)
        self.actionList_Save_As.setObjectName("actionList_Save_As")
        self.actionImport_List = QtWidgets.QAction(BatDownWindow)
        self.actionImport_List.setObjectName("actionImport_List")
        self.menuOperation.addAction(self.actionList_Save_As)
        self.menuOperation.addAction(self.actionImport_List)
        self.menubar.addAction(self.menuOperation.menuAction())

        self.retranslateUi(BatDownWindow)
        QtCore.QMetaObject.connectSlotsByName(BatDownWindow)

    def retranslateUi(self, BatDownWindow):
        _translate = QtCore.QCoreApplication.translate
        BatDownWindow.setWindowTitle(_translate("BatDownWindow", "Batch Download Window"))
        self.btnSelectPath.setText(_translate("BatDownWindow", "Select Path"))
        self.groupBox.setTitle(_translate("BatDownWindow", "添加下载列表"))
        self.label.setText(_translate("BatDownWindow", "File Name"))
        self.label_2.setText(_translate("BatDownWindow", "Link"))
        self.label_3.setText(_translate("BatDownWindow", "Base Link"))
        self.groupBox_2.setTitle(_translate("BatDownWindow", "Down Mode"))
        self.rb1.setText(_translate("BatDownWindow", "M3U8"))
        self.rb2.setText(_translate("BatDownWindow", "Single Thread"))
        self.rb3.setText(_translate("BatDownWindow", "Multi Thread"))
        self.groupBox_3.setTitle(_translate("BatDownWindow", "Combine Mode"))
        self.radioButton.setText(_translate("BatDownWindow", "FFmpeg"))
        self.radioButton_2.setText(_translate("BatDownWindow", "Composition"))
        self.btnDownList.setText(_translate("BatDownWindow", "Down List"))
        self.btnAddLink.setText(_translate("BatDownWindow", "Add Link"))
        self.groupBox_4.setTitle(_translate("BatDownWindow", "Task"))
        self.cbSwTask.setText(_translate("BatDownWindow", "More Task"))
        self.menuOperation.setTitle(_translate("BatDownWindow", "Operation"))
        self.actionList_Save_As.setText(_translate("BatDownWindow", "List Save As"))
        self.actionImport_List.setText(_translate("BatDownWindow", "Import List"))
