# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VipDownUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VDownWindow(object):
    def setupUi(self, VDownWindow):
        VDownWindow.setObjectName("VDownWindow")
        VDownWindow.resize(658, 550)
        self.centralwidget = QtWidgets.QWidget(VDownWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 13, 31, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txtUrl = QtWidgets.QTextEdit(self.centralwidget)
        self.txtUrl.setGeometry(QtCore.QRect(50, 10, 601, 21))
        self.txtUrl.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtUrl.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtUrl.setObjectName("txtUrl")
        self.cboExEng = QtWidgets.QComboBox(self.centralwidget)
        self.cboExEng.setGeometry(QtCore.QRect(430, 40, 221, 22))
        self.cboExEng.setObjectName("cboExEng")
        self.btnGetUrl = QtWidgets.QPushButton(self.centralwidget)
        self.btnGetUrl.setGeometry(QtCore.QRect(560, 70, 91, 23))
        self.btnGetUrl.setObjectName("btnGetUrl")
        self.txtLink = QtWidgets.QTextEdit(self.centralwidget)
        self.txtLink.setGeometry(QtCore.QRect(10, 415, 641, 51))
        self.txtLink.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtLink.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLink.setObjectName("txtLink")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 35, 221, 376))
        self.listView.setObjectName("listView")
        self.pbDownBar = QtWidgets.QProgressBar(self.centralwidget)
        self.pbDownBar.setGeometry(QtCore.QRect(10, 470, 641, 23))
        self.pbDownBar.setProperty("value", 0)
        self.pbDownBar.setObjectName("pbDownBar")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(240, 40, 161, 121))
        self.groupBox.setObjectName("groupBox")
        self.btnDown = QtWidgets.QPushButton(self.groupBox)
        self.btnDown.setGeometry(QtCore.QRect(10, 20, 141, 23))
        self.btnDown.setObjectName("btnDown")
        self.btnDownMerge = QtWidgets.QPushButton(self.groupBox)
        self.btnDownMerge.setGeometry(QtCore.QRect(10, 50, 141, 23))
        self.btnDownMerge.setObjectName("btnDownMerge")
        self.btnMerge = QtWidgets.QPushButton(self.groupBox)
        self.btnMerge.setGeometry(QtCore.QRect(10, 80, 141, 23))
        self.btnMerge.setObjectName("btnMerge")
        self.txtMsg = QtWidgets.QTextEdit(self.centralwidget)
        self.txtMsg.setGeometry(QtCore.QRect(235, 170, 416, 241))
        self.txtMsg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtMsg.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtMsg.setObjectName("txtMsg")
        self.btnStop = QtWidgets.QPushButton(self.centralwidget)
        self.btnStop.setGeometry(QtCore.QRect(560, 100, 91, 23))
        self.btnStop.setObjectName("btnStop")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 70, 120, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.rbFfmpeg = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbFfmpeg.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.rbFfmpeg.setObjectName("rbFfmpeg")
        self.rbNormally = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbNormally.setGeometry(QtCore.QRect(10, 40, 89, 16))
        self.rbNormally.setObjectName("rbNormally")
        VDownWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VDownWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 23))
        self.menubar.setObjectName("menubar")
        self.menuOperate = QtWidgets.QMenu(self.menubar)
        self.menuOperate.setObjectName("menuOperate")
        VDownWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VDownWindow)
        self.statusbar.setObjectName("statusbar")
        VDownWindow.setStatusBar(self.statusbar)
        self.actionClear_List = QtWidgets.QAction(VDownWindow)
        self.actionClear_List.setObjectName("actionClear_List")
        self.actionShow_in_Explorer = QtWidgets.QAction(VDownWindow)
        self.actionShow_in_Explorer.setObjectName("actionShow_in_Explorer")
        self.menuOperate.addAction(self.actionClear_List)
        self.menuOperate.addAction(self.actionShow_in_Explorer)
        self.menubar.addAction(self.menuOperate.menuAction())

        self.retranslateUi(VDownWindow)
        QtCore.QMetaObject.connectSlotsByName(VDownWindow)

    def retranslateUi(self, VDownWindow):
        _translate = QtCore.QCoreApplication.translate
        VDownWindow.setWindowTitle(_translate("VDownWindow", "Vip Down Window"))
        self.label.setText(_translate("VDownWindow", "URL"))
        self.btnGetUrl.setText(_translate("VDownWindow", "Get Play Url"))
        self.txtLink.setHtml(_translate("VDownWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox.setTitle(_translate("VDownWindow", "Download Operation"))
        self.btnDown.setText(_translate("VDownWindow", "DownLoad"))
        self.btnDownMerge.setText(_translate("VDownWindow", "Select Merge File"))
        self.btnMerge.setText(_translate("VDownWindow", "Video Merge"))
        self.btnStop.setText(_translate("VDownWindow", "Task Start"))
        self.groupBox_2.setTitle(_translate("VDownWindow", "Stream Combine"))
        self.rbFfmpeg.setText(_translate("VDownWindow", "FFmpeg"))
        self.rbNormally.setText(_translate("VDownWindow", "Composition"))
        self.menuOperate.setTitle(_translate("VDownWindow", "Operation"))
        self.actionClear_List.setText(_translate("VDownWindow", "Clear List"))
        self.actionShow_in_Explorer.setText(_translate("VDownWindow", "Show in Explorer"))
